# Generated by Django 3.2.12 on 2022-12-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'блоги',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Сounterparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(db_index=True, max_length=150, verbose_name='Фамилия')),
                ('firma', models.CharField(db_index=True, max_length=150, verbose_name='Организация')),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('coment', models.CharField(blank=True, max_length=80, verbose_name='Коментарий')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.сounterparties', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Задолжность',
                'verbose_name_plural': 'Задолжности',
                'ordering': ['-data'],
            },
        ),
    ]
