# Generated by Django 3.2.12 on 2022-12-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
