# Generated by Django 3.2.12 on 2022-12-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('sum', models.IntegerField()),
            ],
        ),
    ]
