# Generated by Django 3.2.12 on 2022-12-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='сounterparties',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_images/'),
        ),
    ]
