# Generated by Django 3.2.12 on 2022-12-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='coment',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
