# Generated by Django 3.2.12 on 2022-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_records_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='coment',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
