# Generated by Django 4.1.5 on 2023-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20221222_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['-data'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='сounterparties',
            name='firma',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='сounterparties',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='сounterparties',
            name='surname',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Фамилия'),
        ),
    ]
