# Generated by Django 3.2.12 on 2022-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsBlonck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='events_images/')),
                ('test', models.TextField()),
            ],
            options={
                'verbose_name': 'Зaпись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
