# Generated by Django 4.1.5 on 2023-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsblonck',
            name='image',
            field=models.ImageField(blank=True, upload_to='events_images/', verbose_name='Фото'),
        ),
    ]
