# Generated by Django 4.1.5 on 2023-02-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventsblonck_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsblonck',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
